name: quiz_wiz
description: "QuizWiz developed by Anita Balotiya."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.1+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # For Network calls
  http: ^1.2.0

  # For State management
  get: ^4.6.6

  # Opening rate us
  url_launcher: ^6.2.6

  # Lottie animation
  lottie: ^3.1.0

  # For storing data (in local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Foreground & Background
  flutter_fgbg: ^0.3.0

  # to get country code
  country_picker: ^2.0.25

  # to use the Firebase Core API
  firebase_core: ^2.31.0

  # to authenticate user
  firebase_auth: ^4.19.5

  # for google sign in
  google_sign_in: ^6.2.1

  # to use the Firebase App Check API
  firebase_app_check: ^0.2.2+5

  # to store data in firebase firestore (DB)
  cloud_firestore: ^4.17.3

  # share app link
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0

  # change_app_package_name: ^1.1.0
  # flutter pub run change_app_package_name:main com.new.package.name

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/icons/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here.
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
